kind: pipeline
type: docker
name: debian-package

steps:
- name: build debian package
  image: ubuntu:20.04
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt install -y debhelper cmake
  - dpkg-buildpackage -uc -us -b

---
kind: pipeline
type: docker
name: unittests

steps:
- name: run unittests
  image: ubuntu:20.04
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - apt update
  - apt install -y build-essential cmake ninja-build
  - mkdir build
  - cd build
  - cmake -DWITH_UNITTESTS=True -GNinja ..
  - ninja gtest
  - ./gtest
