kind: pipeline
type: docker
name: unittests

steps:
- name: run unittests
  image: nx.benfm.de:5000/drone-container:22.04
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - mkdir build
  - cd build
  - cmake -DWITH_UNITTESTS=True -GNinja ..
  - ninja gtest
  - ./gtest
----
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: build packages
  image: nx.benfm.de:5000/drone-container:20.04
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - dpkg-buildpackage -uc -us -b -j2
  - cp -v ../*.deb debian/

- name: push packages
  image: nx.benfm.de:5000/drone-push-ubuntu
  settings:
    repository: ubuntu-focal
  when:
    branch:
    - main
---
kind: pipeline
type: docker
name: ubuntu-jammy

steps:
- name: build packages
  image: nx.benfm.de:5000/drone-container:22.04
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - dpkg-buildpackage -uc -us -b -j2
  - cp -v ../*.deb debian/

- name: push packages
  image: nx.benfm.de:5000/drone-push-ubuntu
  settings:
    repository: ubuntu-jammy
  when:
    branch:
    - main
